#!/bin/bash

function metaframe {

    base_dir=~/.metaframe
    config_dir=${base_dir}/config
    metadata_dir=${base_dir}/metadata
    logs_dir=${base_dir}/logs

    connections_file=${config_dir}/connections.yaml
    log_file=${logs_dir}/etl_log.out

    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
      DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
      SOURCE="$(readlink "$SOURCE")"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    relative_base_path="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    python_executable=${relative_base_path}/../libexec/dist/build_script/build_script
    fzf_binary=${relative_base_path}/../libexec/fzf

    append_line() {
        set -e
        local line file pat lno
        line="$1"
        file="$2"
        name="$3"
        host="${4:-}"
        lno=""

        echo "Update $file:"
        echo -e "$line"
        if [ -f "$file" ]; then
        lno_name=$(\grep -nF "$pat1" "$file" | sed 's/:.*//' | tr '\n' ' ')
        lno_host=$(\grep -nF "$pat2" "$file" | sed 's/:.*//' | tr '\n' ' ')
        fi
        if [ -n "$lno_name" ]; then
        echo "    - Name already exists: line #$lno_name"
        elif [ -n "$lno" ]; then
        echo "    - Host already exists: line #$lno_host"
        else
            [ -f "$file" ] && echo >> "$file"
            echo -e "$line" >> "$file"
        fi
        echo
        set +e
    }

    initialize() {
        echo ""
        echo "Welcome to metaframe!"
        echo ""
        echo "Metaframe needs to initialize the following file structure:"
        echo ""
        echo "~/.metaframe"
        echo "├── config"
        echo "│   └── connections.yaml"
        echo "├── logs"
        echo "└── metadata"
        echo ""
        echo "We'll check if this exists and make it if it doesn't."
        echo "Continue? [Press enter to continue, CTRL-C to exit]"
        read

        mkdir -p ${metadata_dir}
        mkdir -p ${base_dir}
        mkdir -p ${config_dir}
        mkdir -p ${metadata_dir}
        mkdir -p ${logs_dir}
        touch -a ${connections_file}
    }

    file_structure_check () {
        if ([ ! -d ${metadata_dir} ] || [ ! -d ${base_dir} ] || [ ! -f ${connections_file} ]); then
            echo "You need to initialize the file structure first. Run 'mf init'."
            exit
        fi
    }

    if [ $# -eq 0 ]; then
        file_structure_check

        cd ${metadata_dir}
        if command -v bat; then
            dataframe_file="$(pwd)/$(find . -name "*.md" ! -name "*.docs.md" | sed "s/\.md//" | sed 's/^..//' | ${fzf_binary} --preview 'bat {}.md --style=full --color=always; bat {}.docs.md --style=numbers --color=always')".docs.md
        else
            dataframe_file="$(pwd)/$(find . -name "*.md" ! -name "*.docs.md" | sed "s/\.md//" | sed 's/^..//' | ${fzf_binary} --preview 'cat {}.md; cat {}.docs.md')".docs.md
        fi
        if [ -f "${dataframe_file}" ]; then
            ${EDITOR:-vim} "${dataframe_file}"
        fi
    else
        case $1 in

            init)
                initialize
                ;;

            connections)
                file_structure_check
                shift
                case $1 in
                    add)
                        shift
                        while [ $# -gt 0 ]; do
                            case $1 in
                                -n|--name) name="$2"; shift ;;
                                -t|--type) type="$2"; shift ;;
                                -h|--host) host="$2"; shift ;;
                                -u|--username) username="$2"; shift ;;
                                -p|--password) password="$2"; shift ;;
                            esac
                            shift
                        done
                        line1="- name: ${name}\n"
                        line2="  type: ${type}\n"
                        line3="  host: ${host}\n"
                        line4="  username: ${username}\n"
                        line5="  password: ${password}\n"

                        lines=${line1}${line2}${line3}${line4}${line5}
                        append_line "${lines}" ${connections_file} "host: ${host}" "name: ${name}"
                        ;;
                    list)
                        cat ${connections_file}
                        ;;
                    edit)
                        ${EDITOR:-vim} ${connections_file}
                        ;;
                esac
                ;;
            etl)
                file_structure_check
                echo "Running an ETL job against your db (this may take some time)."
                shift
                ${python_executable} $@
                # nohup $(${python_executable}) > ${log_file} &
                ;;
            new)
                shift
                if [ -z $1 ]; then
                    echo "You need to supply a file name."
                else
                    if [ ${1: -3} == ".md" ]; then
                        new_file=${metadata_dir}/$1
                        doc_file=${metadata_dir}/${1: -3}.docs.md
                    else
                        new_file=${metadata_dir}/${1}.md
                        doc_file=${metadata_dir}/${1}.docs.md
                    fi
                    echo "Creating ${new_file} and ${doc_file}."
                    mkdir -p "${new_file%/*}" && touch "$new_file" && touch "$doc_file"
                    $EDITOR $new_file
                fi
                ;;
            -a|--all)
                file_structure_check

                cd ${metadata_dir}
                if command -v bat; then
                    dataframe_file="$(pwd)/$(find . -name "*.md" | ${fzf_binary} --preview 'bat {} --style=full --color=always')"
                else
                    dataframe_file="$(pwd)/$(find . -name "*.md" | ${fzf_binary} --preview 'cat {}')"
                fi
                if [ -f "${dataframe_file}" ]; then
                    ${EDITOR:-vim} "${dataframe_file}"
                fi
                ;;
            logs)
                ${EDITOR:-vim} ${log_file}
                ;;
            *)
                echo "Command not found."
                ;;
        esac
   fi
}

metaframe $@
