COLUMN_DETAILS_DELIMITER = "## Column details"
PARTITIONS_DELIMITER = "## Partition info"
USAGE_DELIMITER = "## Usage info"
UGC_DELIMITER = "-" * 79
DEFINED_METRICS_DELIMITER = "```metrics"
METRICS_DELIMITER = "## Metrics"
TAGS_DELIMITER = "## Tags"
BLOCK_END_DELIMITER = "```"
