SELECT
  c.SCHEMANAME,
  c.TABLENAME,
  t.TABLETYPE,
  c.COLUMNNAME,
  c.COLUMNNUMBER,
  varchar(COLUMNDATATYPE,5000)
FROM SYSVW.SYSCOLUMNSVIEW c
LEFT JOIN SYSVW.SYSTABLESVIEW t
  ON c.SCHEMANAME = t.SCHEMANAME
  AND c.TABLENAME = t.TABLENAME
